### ISSUE TITLE
node 11.12.0 build error

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/node-rpm#161]
@danbev I saw this error while building locally:

```
../src/inspector_agent.cc: In member function 'int node::inspector::NodeInspectorClient::connectFrontend(std::unique_ptr<node::inspector::InspectorSessionDelegate>, bool)':
../src/inspector_agent.cc:479:9: error: 'make_unique' is not a member of 'std'
         std::make_unique<ChannelImpl>(env_, client_, getWorkerManager(),
         ^
../src/inspector_agent.cc:479:37: error: expected primary-expression before '>' token
         std::make_unique<ChannelImpl>(env_, client_, getWorkerManager(),
                                     ^
../src/inspector_agent.cc:479:45: warning: left operand of comma operator has no effect [-Wunused-value]
         std::make_unique<ChannelImpl>(env_, client_, getWorkerManager(),
                                             ^
../src/inspector_agent.cc:479:71: warning: right operand of comma operator has no effect [-Wunused-value]
         std::make_unique<ChannelImpl>(env_, client_, getWorkerManager(),
                                                                       ^
make[1]: *** [/opt/app-root/src/rpmbuild/BUILD/node-v11.2.0-rh/out/Release/obj.target/node_lib/src/inspector_agent.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [node] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.fTYdNg (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.fTYdNg (%build)
```

**Comment by danbev** [comment]
@helio-frota Looks like we need to update the compiler version to at least `4.9` to support `make_unique`.

**Comment by helio-frota** [comment]
@danbev ok thanks for the tip.
I'm working on that

**Comment by helio-frota** [comment]
Reopen because it was a confusion.

The build was OK because was using version 11.1.0 instead 11.2.0 which has the bits that causes error with old gcc version.

(11.1.0 instead 11.2.0)
https://travis-ci.org/nodeshift/node-rpm/builds/456998722#L750

Another thing is that for some reason the gcc version was not updated when using devtoolset-7:

```
RUN yum install -y rpmdevtools         \
                   git 	devtoolset-7-gcc devtoolset-7-gcc-c++     
```

```
node-rpm v11.2.0🔒 ✅  docker run -it bucharestgold/node-rpm /bin/bash
bash-4.2# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
```

So I'll continue investigating this (changing and building locally) until get an updated version of gcc and 11.2.0 working. Then I'll send the PR again.

**Comment by helio-frota** [comment]
A bit more information on this.

The devtoolset-7 package is not installed.

Following this documentation: https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/

I get this message:

```
No package devtoolset-7 available.
```

![screenshot_6](https://user-images.githubusercontent.com/6443576/48777590-c13a7380-ecb1-11e8-983a-ce8d68d61e91.png)

Also make is already installed, and we are using a 7.3 version of centos and the latest image was published two years ago according dockerhub.

I'll create issue for each part.

**Comment by danbev** [comment]
We should be able to use gcc 4.9 or higher so perhaps there is a version lower than 7 available. Might be worth looking into.

**Comment by helio-frota** [comment]
I saw that Node.js 11.2.0 upstream is using centos7-gcc6 on jenkins.
~I agree that we should use lower than 7 -- also would be good to use the same version as Node.js upstream.~

Update: Node.js upstream uses several different environments.

**Comment by helio-frota** [comment]
closing this. 11.2.0 released https://github.com/nodeshift/node-rpm/releases/tag/v11.2.0
