### ISSUE TITLE
Document release issues from 8.1.4

### ISSUE THREAD

**Issue by lance** [bucharest-gold/node-rpm#22]
With @danbev on leave for a while, and a security release required, @helio-frota jumped on it and got an RPM built and released in a day. But there were issues along the way. We should document these, and determine what solutions we can apply to prevent them in the future.

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/node-rpm/tree/v8.x-staging#basic-steps-to-release-new-rpm-versions-on-github
