### ISSUE TITLE
Consider removing master branch

### ISSUE THREAD

**Issue by danbev** [bucharest-gold/node-rpm#28]
Currently the master branch is not used for anything. Instead only the staging branches are used and when we need a new staging branch we should just an existing one as the base. Just merging back to master for the sake of it being up to date seems a little pointless and risks it lagging behind and be out of date.

**Comment by helio-frota** [comment]
I totally agree.
Also this will make things more related to the main goal of the project.

>This purpose of this project is to create RPMs targeted for Fedora and RHEL to allow us to help identify issues early and contribute changes upstream when possible.

And discard some confusion on the need to update the master.
