### ISSUE TITLE
Fix code climat label

### ISSUE THREAD

**Issue by danbev** [bucharest-gold/node-rpm#32]
After the renaming of the project the code climat label does not work.

**Comment by helio-frota** [comment]
@danbev You maybe mean license-reporter ?
If yes, then was updated.
I think is good to delegate to @lance

**Comment by lance** [comment]
![screen shot 2017-09-06 at 1 17 27 pm](https://user-images.githubusercontent.com/15952/30125233-d04e0f82-9305-11e7-883d-e5bd09c9f089.png)

Looks like code climate won't work for this project. :/

**Comment by helio-frota** [comment]
@lance I'm going to remove license-reporter from my personal account.
Then you can add on your account or try something with organization level etc.

**Comment by helio-frota** [comment]
Done. 
Removed : license-reporter, szero, roi, node-metadata and genet.
