### ISSUE TITLE
NPM install fails on openshift/base-centos7

### ISSUE THREAD

**Issue by lance** [bucharest-gold/node-rpm#79]
When I run an instance of the `openshift/base-centos7` container and install either the 8.9.1 or the 9.1.0 `node` RPMs along with the corresponding `npm` RPM, I am unable to install anything using `npm install`. Below is a transcript and log output.

The error is `ERR! Failed to set ECDH curve` which is thrown [here](https://github.com/nodejs/node/blob/c2d63a9785426d4c37e3eec8c3de1dfad741c3d4/src/node_crypto.cc#L1131).

<details><summary>
~/src docker run -it openshift/base-centos7 /bin/bash
</summary>
<code><pre>
bash-4.2# yum install -y https://github.com/bucharest-gold/node-rpm/releases/download/v8.9.1/rhoar-nodejs-8.9.1-1.el7.centos.x86_64.rpm
Loaded plugins: fastestmirror, ovl
rhoar-nodejs-8.9.1-1.el7.centos.x86_64.rpm                                                                                                                               | 7.3 MB  00:00:02
Examining /var/tmp/yum-root-CsGGtc/rhoar-nodejs-8.9.1-1.el7.centos.x86_64.rpm: 1:rhoar-nodejs-8.9.1-1.el7.centos.x86_64
Marking /var/tmp/yum-root-CsGGtc/rhoar-nodejs-8.9.1-1.el7.centos.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package rhoar-nodejs.x86_64 1:8.9.1-1.el7.centos will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================================================================================================================================
 Package                                Arch                             Version                                        Repository                                                         Size
================================================================================================================================================================================================
Installing:
 rhoar-nodejs                           x86_64                           1:8.9.1-1.el7.centos                           /rhoar-nodejs-8.9.1-1.el7.centos.x86_64                            25 M

Transaction Summary
================================================================================================================================================================================================
Install  1 Package

Total size: 25 M
Installed size: 25 M
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : 1:rhoar-nodejs-8.9.1-1.el7.centos.x86_64                                                                                                                                     1/1
  Verifying  : 1:rhoar-nodejs-8.9.1-1.el7.centos.x86_64                                                                                                                                     1/1

Installed:
  rhoar-nodejs.x86_64 1:8.9.1-1.el7.centos

Complete!
bash-4.2# yum install -y https://github.com/bucharest-gold/node-rpm/releases/download/v8.9.1/npm-5.5.1-1.8.9.1.1.el7.centos.x86_64.rpm
Loaded plugins: fastestmirror, ovl
npm-5.5.1-1.8.9.1.1.el7.centos.x86_64.rpm                                                                                                                                | 4.1 MB  00:00:01
Examining /var/tmp/yum-root-CsGGtc/npm-5.5.1-1.8.9.1.1.el7.centos.x86_64.rpm: 1:npm-5.5.1-1.8.9.1.1.el7.centos.x86_64
Marking /var/tmp/yum-root-CsGGtc/npm-5.5.1-1.8.9.1.1.el7.centos.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package npm.x86_64 1:5.5.1-1.8.9.1.1.el7.centos will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================================================================================================================================
 Package                       Arch                             Version                                                  Repository                                                        Size
================================================================================================================================================================================================
Installing:
 npm                           x86_64                           1:5.5.1-1.8.9.1.1.el7.centos                             /npm-5.5.1-1.8.9.1.1.el7.centos.x86_64                            18 M

Transaction Summary
================================================================================================================================================================================================
Install  1 Package

Total size: 18 M
Installed size: 18 M
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : 1:npm-5.5.1-1.8.9.1.1.el7.centos.x86_64                                                                                                                                      1/1
  Verifying  : 1:npm-5.5.1-1.8.9.1.1.el7.centos.x86_64                                                                                                                                      1/1

Installed:
  npm.x86_64 1:5.5.1-1.8.9.1.1.el7.centos

Complete!
bash-4.2# npm install -g nodemon
npm ERR! Failed to set ECDH curve

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/app-root/src/.npm/_logs/2017-11-10T21_16_25_689Z-debug.log
bash-4.2# cat /opt/app-root/src/.npm/_logs/2017-11-10T21_16_25_689Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '-g', 'nodemon' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose npm-session 0d67e0b58c365cdd
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for nodemon@latest Failed to set ECDH curve
8 verbose stack Error: Failed to set ECDH curve
8 verbose stack     at Object.createSecureContext (_tls_common.js:114:15)
8 verbose stack     at Object.exports.connect (_tls_wrap.js:1047:48)
8 verbose stack     at HttpsAgent.createConnection (https.js:111:22)
8 verbose stack     at HttpsAgent.createSocket (/usr/lib/node_modules/npm/node_modules.bundled/pacote/node_modules/make-fetch-happen/node_modules/agentkeepalive/lib/_http_agent.js:271:26)
8 verbose stack     at HttpsAgent.createSocket (/usr/lib/node_modules/npm/node_modules.bundled/pacote/node_modules/make-fetch-happen/node_modules/agentkeepalive/lib/agent.js:77:11)
8 verbose stack     at HttpsAgent.addRequest (/usr/lib/node_modules/npm/node_modules.bundled/pacote/node_modules/make-fetch-happen/node_modules/agentkeepalive/lib/_http_agent.js:240:10)
8 verbose stack     at new ClientRequest (_http_client.js:258:16)
8 verbose stack     at Object.request (http.js:38:10)
8 verbose stack     at request (https.js:239:15)
8 verbose stack     at fetch.Promise (/usr/lib/node_modules/npm/node_modules.bundled/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:54:17)
8 verbose stack     at new Promise (<anonymous>)
8 verbose stack     at fetch (/usr/lib/node_modules/npm/node_modules.bundled/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:41:10)
8 verbose stack     at retry (/usr/lib/node_modules/npm/node_modules.bundled/pacote/node_modules/make-fetch-happen/index.js:330:14)
8 verbose stack     at /usr/lib/node_modules/npm/node_modules.bundled/pacote/node_modules/promise-retry/index.js:29:24
8 verbose stack     at <anonymous>
9 verbose cwd /opt/app-root/src
10 verbose Linux 4.9.44-linuxkit-aufs
11 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "nodemon"
12 verbose node v8.9.1
13 verbose npm  v5.5.1
14 error Failed to set ECDH curve
15 verbose exit [ 1, true ]
</pre></code>
</details>

**Comment by danbev** [comment]
~I've not been able to reproduce this yet. The following commands succeed for me:~
<details>
<summary>console output</summary>

```console

bash-4.2# yum install -y https://github.com/bucharest-gold/node-rpm/releases/download/v8.9.1/rhoar-nodejs-8.9.1-1.el7.centos.x86_64.rpm
Loaded plugins: fastestmirror, ovl
rhoar-nodejs-8.9.1-1.el7.centos.x86_64.rpm                                                        | 7.3 MB  00:00:02
Examining /var/tmp/yum-root-aHPQsN/rhoar-nodejs-8.9.1-1.el7.centos.x86_64.rpm: 1:rhoar-nodejs-8.9.1-1.el7.centos.x86_64
Marking /var/tmp/yum-root-aHPQsN/rhoar-nodejs-8.9.1-1.el7.centos.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package rhoar-nodejs.x86_64 1:8.9.1-1.el7.centos will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=========================================================================================================================
 Package              Arch           Version                       Repository                                       Size
=========================================================================================================================
Installing:
 rhoar-nodejs         x86_64         1:8.9.1-1.el7.centos          /rhoar-nodejs-8.9.1-1.el7.centos.x86_64          25 M

Transaction Summary
=========================================================================================================================
Install  1 Package

Total size: 25 M
Installed size: 25 M
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : 1:rhoar-nodejs-8.9.1-1.el7.centos.x86_64                                                              1/1
  Verifying  : 1:rhoar-nodejs-8.9.1-1.el7.centos.x86_64                                                              1/1

Installed:
  rhoar-nodejs.x86_64 1:8.9.1-1.el7.centos

Complete!
bash-4.2# yum install -y https://github.com/bucharest-gold/node-rpm/releases/download/v8.9.1/npm-5.5.1-1.8.9.1.1.el7.centos.x86_64.rpm
Loaded plugins: fastestmirror, ovl
npm-5.5.1-1.8.9.1.1.el7.centos.x86_64.rpm                                                         | 4.1 MB  00:00:01
Examining /var/tmp/yum-root-aHPQsN/npm-5.5.1-1.8.9.1.1.el7.centos.x86_64.rpm: 1:npm-5.5.1-1.8.9.1.1.el7.centos.x86_64
Marking /var/tmp/yum-root-aHPQsN/npm-5.5.1-1.8.9.1.1.el7.centos.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package npm.x86_64 1:5.5.1-1.8.9.1.1.el7.centos will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=========================================================================================================================
 Package     Arch           Version                                 Repository                                      Size
=========================================================================================================================
Installing:
 npm         x86_64         1:5.5.1-1.8.9.1.1.el7.centos            /npm-5.5.1-1.8.9.1.1.el7.centos.x86_64          18 M

Transaction Summary
=========================================================================================================================
Install  1 Package

Total size: 18 M
Installed size: 18 M
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : 1:npm-5.5.1-1.8.9.1.1.el7.centos.x86_64                                                               1/1
  Verifying  : 1:npm-5.5.1-1.8.9.1.1.el7.centos.x86_64                                                               1/1

Installed:
  npm.x86_64 1:5.5.1-1.8.9.1.1.el7.centos

Complete!
bash-4.2#  npm install -g nodemon
/usr/bin/nodemon -> /usr/lib/node_modules/nodemon/bin/nodemon.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/nodemon/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ nodemon@1.12.1
added 116 packages and updated 1 package in 6.406s

```
</details>

**Comment by danbev** [comment]
Doing a `yum install -y openssl` would allow the commands to succeed. I'll take a closer look at the base images and see what they provide.

**Comment by lance** [comment]
Confirmed that installing openssl fixes it. Do you think this issue should be closed?

**Comment by danbev** [comment]
> Do you think this issue should be closed?

I think so, I've tried this using the latest centos (`docker run -ti centos`) and it works without having to install openssl. So I'll go ahead and close this.
